version: "3.7"

networks:
  todolist:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=todolist
      - MYSQL_PASSWORD=todolist
      - TZ = Asia/Shanghai
    ports:
      - "3309:3306"
    networks:
      - todolist
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config/mysql:/var/lib/mysql
      - ./logs/mysql/log:/var/log/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - todolist

  etcd-keeper:
    image: "evildecay/etcdkeeper:latest"
    container_name: etcd-keeper
    environment:
      - ETCD_HOSTS=http://etcd:2379
      - SW_STORAGE_ETCD_CLUSTER_NODES=etcd:2379
      - HOST=127.0.0.1
      - HOSTNAME=etcd-keeper
    links:
      - etcd
    ports:
      - "8080:8080"
    networks:
      - todolist

  etcd:
    container_name: etcd
    image: "quay.io/coreos/etcd:v3.5.5"
    restart: on-failure
    privileged: true
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - ETCD_API=3
      - ETCD_CERT_FILE="/path/to/server.crt"
      - ETCD_KEY_FILE="/path/to/server.key"
      - ETCD_AUTH="simple"
      - ETCD_AUTH_USER="todolist"
      - ETCD_AUTH_PASSWORD="todolist"
    ports:
      - "2380:2379"
    networks:
      - todolist

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=todolist
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - "6380:6379"
    volumes:
      - /usr/local/redis:/usr/local/redis
    networks:
      - todolist

